// File Overview
// Defines shared visual, ecological, interaction, lifecycle, sound,
// and performance parameters.

// 1. A shared scale for the ecology's rhythms
// Visual, interaction, lifecycle, sound, and performance parameters
// are gathered here so that all lifeforms act along a shared scale.
(() => {
  "use strict";

// 2. Each lifeform retains its own rhythm within the shared scale
  // This file creates and freezes the shared scale; runtime state, timers,
  // and caches remain with the lifeforms and systems that use its parameters.
  // Parameter suffixes: Ms milliseconds, Scl scale, Rad radius, Alph opacity, Tps updates per second.
  // Other suffixes: Prog progress, Dur duration, Intr interval, Tgt target.
  function create({ eco, zones, userGlow: userImpactGlow }) {
    return {
    userGlow: userImpactGlow,
  // Predator's visual and movement scales determine
  // how it approaches the audience and captures attention.
    predator: {
      speedMin: 0.15,
      speedMax: 0.5,
      outlineWaveAmp: 13.5,
      outlineSpeed: 0.35,
      waveSpaceScale: 0.7,
      outlinePoints: 42,
      lineCchTps: 12,
      breathAmp: 0.02,
      breathPeriod: 1.45,
      x0: 0.02,
      x1: 0.98,
      y0: zones.predator.y0,
      y1: zones.predator.y1,
      baitSizeMul: { dot: 0.82, alert: 0.78, notice: 1.35 },
    },
  // Guardian's care and drift scales control attentional recovery and its visible feedback.
    guardian: {
      rspd: 0.5 / eco.simFps,
      waveSpeed: 0.45,
      waveSegments: 48,
      waveCacheTps: 12,
      outerRingAmp: 6,
      innerRingAmp: 5.5,
      outerGlowAmp: 8,
      innerGlowAmp: 6,
      plusBreathMin: 0.5175,
      plusBreathMax: 1.1,
      plusBrthSpd: 1.8,
      plusAlphMul: 1.3,
      drftMnsWghtMul: 1.5,
      drift: {
        sizeMul: 1.68858,
        weightMul: 1.175,
        idleAlphaMin: 82.8,
        idleAlphaMax: 147.2,
        dirSmthMs: 294,
        posSmthMs: 386,
        alphaSmoothMs: 138,
        alphaSoftKnee: 220,
        alphaSoftRange: 35,
        minScrnWght: 1.35,
        frameMsMax: 50,
        motionSpeedOff: 6,
        motionSpeedOn: 12,
        motionSpeedMax: 30,
        mtnSpdFltrMs: 202,
        mtnTxSpdMin: 0.05,
        motionAttackMs: 221,
        mtnFreeMs: 598,
        mtnAlphHoldMs: 1380,
        motionAlphaMin: 242,
        motionAlphaMax: 255,
        motionSizeMul: 1.04,
        mtnWghtMul: 1.02,
      },
      trckPluSizMul: 1.034,
      attnNearPddng: 49,
      attnGraceMs: 322,
      attnLvHoldMs: 1840,
      attnDlyMs: 1380,
      attnApprMs: 1380,
      attnRestoreMs: 1840,
      attnSpdMulMin: 2,
      attnSpdMulMax: 3,
      attnFarDist: 480,
      attnArcScale: 0.8,
      attnArcTurnMs: 414,
      attnRtrnSpdMul: 1.4,
      attnStopDist: 76,
      attnMantPddng: 10,
      attnKeepTol: 6,
      lngrDrftScl: 1,
      plus: {
        rangeScale: 1.6,
        approachMsMin: 2000,
        approachMsMax: 4200,
        forwardMin: 0.46,
        forwardMax: 0.96,
        sideSpread: 0.38,
        groupNMin: 2,
        groupNMax: 3,
        groupShrMin: 0.62,
        groupShrMax: 0.76,
        groupFrwrdMin: 0.56,
        groupFrwrdMax: 0.86,
        groupSideSprd: 0.26,
        grouCntGapMin: 0.2,
        groupRadMin: 0.055,
        groupRadMax: 0.13,
        collisionGap: 0.1,
        otlrGroGapMin: 0.2,
        otlrGroGapMax: 0.34,
        strtDlyMaxMs: 322,
        wander: 0.035,
        mmbrWndrMin: 0.008,
        mmbrWndrMax: 0.028,
        wanderSpeedMin: 0.22,
        wanderSpeedMax: 0.46,
      },
      actvDlyMs: 1500,
      focusMs: 5000,
      attnHoldMs: 5000,
      candHoldPddng: 18,
      candLvGrcMs: 2800,
      lureBrkRadScl: 0.55,
      lureBrkCnfrmMs: 1600,
      lureBrkGrcMs: 250,
      relTmngScl: 1.5,
      // The invitation window lasts longer than acceptance confirmation and signal travel,
      // giving a second participant time to understand and respond intentionally.
      collab: {
        offerMs: 18000,
        acceptMs: 3000,
        maxAccepts: 2,
        signal: {
          travelMinMs: 6000,
          travelMaxMs: 12000,
          travelScale: 0.55,
          stopDistance: 76,
          accptRadScl: 1.85,
          arrivalHoldMs: 5000,
          farOffsetMs: 2500,
          farRadiusScale: 1.5,
          fadeOutMs: 2000,
          inputGraceMs: 2800,
          pulseMs: 6000,
          diameter: 54,
          visualScale: 0.6,
          breathScale: 0.04,
        },
        pkt: {
          sendIntervalMs: 4000,
          sendIntrJttr: 0,
          sendMs: 4000,
          sendDurJitter: 0,
          visualScale: 0.74,
          dataOffsetY: 0,
          leftArrowWidth: 10.5,
          mddlArrwWdth: 6.6,
          rghtArrwWdth: 11.2,
          arrwHalfHght: 16.2,
          arrowScale: 1.05,
          dataGap: 5.4,
          arrowLift: 1,
          dotGapOffset: 1.5,
          arrowGapOffset: -0.4,
          dataWeight: 2.5,
          dataBaseAlpha: 80,
          dataPeakAlpha: 255,
          alphaBoost: 30,
          symbolDriftY: 2,
          arrowCurve: 1.17,
          arrwShldDpth: 0.26,
          arrwShldScl: 0.76,
          arrowTipRound: 0.42,
          dotBreathMs: 4000,
          dotBreathScale: 0.08,
          arrivalTighten: 0.025,
          slotRadius: 6.8,
          slotWeight: 1.8,
          slotLineAlph: 255,
          slotFillAlpha: 255,
          progFillAlph: 255,
          progressInset: 2.2,
          reticleColor: [108, 216, 226],
          dotWaveAmp: 0.48,
          dotWaveSpeed: 0.34,
          rippleWaveAmp: 1.15,
          rpplWaveSpd: 0.17,
          waveSteps: 36,
          rippleLifeMs: 4600,
          rpplMinRad: 3,
          rpplMaxRad: 32,
          rpplSizeScl: 2.325,
          rpplAlphBst: 50,
          rpplAlphScl: 0.65,
          rpplAlphDrop: 15,
          rippleWeight: 1.35,
          lctrActvMs: 1500,
          locatorRestMs: 4000,
          locatorOffsetX: 23,
          locatorOffsetY: -6,
          lctrCrssSize: 3.2,
          lctrTickRad: 8,
          lctrTickLngth: 2.5,
          locatorWeight: 2.2,
          lctrPeakAlph: 240,
          followMs: 1600,
          targetMaxSpeed: 34,
          curveBendMin: 10,
          curveBendMax: 27,
          driftMin: 1.4,
          driftMax: 3.6,
          drftPrdMinMs: 4200,
          drftPrdMaxMs: 7200,
          hoverRadius: 2.6,
          hoverPeriodMs: 5800,
          gazeMtnScl: 0.2,
          gazeMtnEaseMs: 320,
          captureEaseMs: 520,
          cptrFllwMs: 420,
          cptrMaxSpd: 110,
          settleRadius: 10,
          turnEaseMs: 600,
          turnMaxTurRat: 1.5,
          turnMtnThresh: 0.04,
          progTurnEaseMs: 1100,
          progTurRatMax: 0.8,
          progTurnRetrMs: 500,
        },
        link: {
          gap: 18,
          triLength: 8.2,
          triHalfWidth: 4.4,
          triRound: 0.18,
          triAlphaScale: 1.25,
          bendScale: 0.12,
          bendMax: 42,
          drift: 5.5,
          driftSpeed: 0.00105,
          shapeNodeAmps: [3.3, 5.8, 4.1],
          shpNodePrdsMs: [
            3400, 4600, 5900,
          ],
          shapeLongDrift: 2,
          shapeTension: 0.9,
          dashLengthMin: 2.2,
          dashLengthMax: 7.2,
          dashGapMin: 5.8,
          dashGapMax: 13.5,
          dashAlphMinScl: 0.3,
          dashAlphMaxScl: 1,
          dashVrntN: 127,
          dashCurveSteps: 12,
          dashSpeed: 22,
          weight: 1.8,
          alphaMin: 55,
          alphaMax: 100,
          alphaBoost: 45,
          triAlphaBoost: 45,
          fadeInMs: 1500,
          fadeOutMs: 1500,
          elasticStiff: 72,
          elasticDamp: 14,
          elasticMaxLag: 11,
          motionSmooth: 8,
          mtnFullSpd: 600,
          mtnFlowBst: 0.2,
          triBreathAmp: 0.11,
          triBreathMs: 2600,
        },
      },
// As a lifeform returns to a BasicCell, it gradually separates, contracts,
// and fades back to the shared point of origin.
      cellReturn: {
        durationMs: 16770,
        detachMinMs: 5850,
        detachMaxMs: 7800,
        shrinkDurMs: 4030,
        colorDurMs: 4082,
        morphDelayMs: 715,
        morphDurMs: 4225,
        spcFadeEndShr: 0.65,
        cellShoStrShr: 0.55,
        minusFadeDurMs: 2444,
        companionScale: 0.8,
        mateSizeSclMin: 1.05,
        mateSizeSclMax: 1.45,
        companionGap: 6,
        targetAlpha: 0.05,
      },
      relPairColdMs: 12000,
      releaseGraceMs: 2000,
      leaveGraceMs: 3000,
      careGazePddng: 110,
      carePnlPddng: 72,
      careCnclFadeMs: 2500,
      careTimeoutMs: 60000,
      careFnshFadeMs: 2500,
      participantMin: 3,
      participantMax: 4,
      progressColor: [209, 255, 173],
      progressWeight: 11.9,
      progressAlpha: 250,
      progDoneHoldMs: 1000,
      shrdProgHoldMs: 1300,
      progRotScl: 0.2,
      progRotTurnMs: 414,
// Scanning and relational care unfold at a gradual pace.
      scanMs: 3864,
      scanFadeInMs: 920,
      scanFadeOutMs: 3680,
      scanLatFadStrM: 2300,
      scanLateFadeMs: 644,
      relScanMs: 5023.2,
      relScaFadInMs: 1196,
      relScaFadOutMs: 4784,
      shrdScaFadAtMs: 2990,
      relScaLatFadMs: 837.2,
      scanLatAlpScl: 0.5,
      scanWaveAlpha: 25.2,
      scanWaveWeight: 3.1,
      scanWaveAmp: 6,
      scanWavAmpMinS: 0.28,
      scanWavAmpMaxS: 1,
      scanShpShowRad: 40,
      scanWavePntN: 36,
      scanWavSmtPss: 5,
      scanWavMrpAmn: 0.12,
      scanWavRotDrf: 0.04,
      scanCntrPnts: 36,
      scanCntSmtPss: 3,
      scanCntrRadScl: 0.019,
      scanCntrMaxAmp: 18,
      scanOvalMin: 0.015,
      scanOvalMax: 0.024,
      scanCntLopMin: 0.0045,
      scanCntLopMax: 0.009,
      scanCntrTriMin: 0.0045,
      scanCntrTriMax: 0.009,
      scanGloAlpScl: 0.05,
      scanGloWghScl: 4.5,
      scanGlowBlur: 32,
      scanGloShdAlp: 0.22,
      scanGloOtrAlpS: 0.025,
      scanGloOtrWghS: 7,
      scanGloOtrBlu: 52,
      scanGloOtrShdA: 0.12,
      scanPulseSpeed: 0.0022,
      scanPulseAmp: 1.8,
      scanPlsAlphMin: 0.9,
      userGlowScl: userImpactGlow.scale,
      userGlowAlph: userImpactGlow.alpha,
      userGlowSrcScl: userImpactGlow.sourceScale,
      userGloSrcAlp:
        userImpactGlow.srcAlphScl,
      userGlowPlsScl: userImpactGlow.pulseScale,
      userGlowPlsSpd: userImpactGlow.pulseSpeed,
      userGloFadInMs: userImpactGlow.fadeInMs,
      userGloFadOutM: userImpactGlow.fadeOutMs,
      // Appearance order, layout, and text hierarchy of the care panel
      panelFadeInMs: 4140,
      pnlShowLeadMs: 0,
      pnlTypeDlyMs: 644,
      pnlSpcTexShoMs: 2300,
      pnlSpcTexGapMs: 368,
      panelFadeOutMs: 1104,
      panelWidth: 344.2,
      panelHeight: 157,
      pnlTopExpn: 5,
      panelOffset: 12,
      pnlEdgePddng: 14,
      pnlPddngLeft: 11,
      pnlPddngRght: 11,
      pnlPddngTop: 11,
      pnlPddngBttm: 11,
      pnlDotTextGap: 8,
      pnlEllpsOffstX: -30,
      pnlEllpsRadX: 100,
      pnlEllpsRadY: 50,
      pnlEllStrAng: Math.PI,
      pnlRankOffst: [
        { x: 0, y: -10 },
        { x: -4, y: 0 },
        { x: -20, y: 1 },
        { x: -34, y: -14 },
        { x: -20, y: -20 },
      ],
      pnlExtDotOffY: 0,
      pnlSttDotOffY: 4,
      pnlMrkRowOffY: 10,
      pnlBgAlph: 150,
      pnlCntAlpScl: 0.86,
      panelTextColor: [163, 204, 131],
      panelTextAlpha: 230,
      pnlBodTexAlp: 240,
      pnlFontWght: 600,
      pnlSpcFontWght: 600,
      pnlMrkFonWgh: 500,
      pnlMrkrOffstY: 3,
      pnlSttsIconGap: 10,
      pnlSttIcoWdt: 14.4256,
      pnlSttIcoHgh: 17.31072,
      pnlSttIcoWgh: 1.8,
      pnlSttIcoOffY: 3.7,
      pnlSttIcoAlp: 255,
      pnlDotMinSize: 4,
      pnlDotMaxSize: 22,
// Repair leaves behind a seed, and the seed carries care forward into new life.
      repairUseLimit: 3,
      rprTxMs: 1656,
      rprSclPerUse: 0.9,
      rprRingWght: 0.82,
      rprAlphPerUse: 0.86,
      seedCountMin: 1,
      seedCountMax: 2,
      seedSpreadMin: 28,
      seedSpreadMax: 42,
      seedScale: 0.45,
      seedTxMs: 2760,
      seedAlpha: 185,
      seedGlowAlpha: 0.12,
      seedGlowBlur: 5.6,
      seedGloFadOutM: 2300,
      seedFloatX: 3,
      seedFloatY: 5,
      seedFltEasInMs: 1656,
      seedFltPrdXMs: 8464,
      seedFltPrdYMs: 6716,
      seedCellRadius: 120,
      seedRegrDlyMs: 18400,
      seedCellApprMs: 2365,
      seedCellOffstX: 8,
      seedCellOffstY: 6,
      seedCelFadOutM: 2760,
      seedGuaBrtDlyM: 1380,
      seedGuaBrtMs: 2760,
      crssGrdOvrlp: 0.45,
      crossAttachMs: 2944,
      crossReturnMs: 2024,
      crossSizeScale: 1.48,
      crssWghtScl: 1.32,
      crossAlphaMin: 242,
      crossAlphaMax: 255,
      crssAlphOutMs: 644,
      crossCareMs: 920,
      symblMnsTxMs: 1500,
      symblCrssMs: 2500,
      symblCrssOutMs: 1500,
      symblCrssInMs: 1500,
      limitSizeScale: 0.88,
      lmtAlphScl: 0.92,
      lmtTxMs: 2944,
      lmtCutLmt: 6,
      guardClrMs: 2300,
      postClrWaiMinM: 460,
      postClrWaiMaxM: 1380,
      postClrWaiFasS: 0.35,
      clrSpcScl: 0.96,
      clrTypeAlphMul: 0.93,
      clrSpcTxMs: 2760,
      clrTypeCutLmt: 6,
      suppSpdSclMin: 2.4,
      suppSpdSclMax: 6,
      suppChsTmtMs: 11960,
      crssPrstTmtMs: 10000,
      suppExiShrMs: 1380,
      shldSpdSclMin: 2.2,
      shldSpdSclMax: 5.4,
      apprSpdFarDist: 480,
      shldApprGap: 18,
      guardGrowScl: 1.45,
      guardWrapPddng: 1.35,
      clearEndScale: 0.08,
      careMoveMinMs: 3220,
      careMoveMaxMs: 5520,
      careMovFarDis: 480,
      careSettleMs: 1840,
      careLineAlpha: 80,
      careLineWeight: 2,
      carePartN: 6,
      careParSizMin: 3,
      careParSizMax: 5.8,
      careParAlpMin: 130,
      careParAlpMax: 245,
      carePartClr: [163, 204, 131],
      carePartBrthMs: 1656,
      careFlowCycles: 1.4,
      careFloFadShr: 0.14,
      careBstDlyMs: 460,
      careBstTxMs: 2760,
      careSizeScale: 1.12,
      careAlphaScale: 1.1,
      careBoostLimit: 6,
      careParentMin: 1,
      careParentMax: 2,
      careMateNMin: 1,
      careMateNMax: 2,
      careChldSclMin: 0.95,
      careCellSclMax: 1.45,
      careMatAlpMin: 200,
      careMatAlpMax: 250,
      careMateWght: 2.2,
      careMateRadScl: 0.8,
      careMateMs: 27600,
      careMateDlyMs: 920,
      careMatFadInMs: 2760,
      careMatFadOutM: 2300,
      birthChance: 0.3,
      brthMoveProg: 0.75,
      birthRevealMs: 2760,
      brthInitScl: 0,
      brthShowScl: 0.45,
      birthGrowthMs: 55200,
      birthOffset: 28,
      driftPluses: {
        countMin: 5,
        countMax: 10,
        natScttrAttm: 24,
        natGroupNMin: 2,
        natGroupNMax: 3,
        natGroupShrMin: 0.6,
        natGroupShrMax: 0.7,
        groupCntrMin: 24,
        groupCntrMax: 82,
        grouCntGapMin: 48,
        natGroupRadMin: 12,
        natGroupRadMax: 30,
        natDnsGapMin: 10,
        natDnsGapMax: 24,
        natSprsRadMin: 62,
        natSprsGapMin: 42,
        natSprsGapMax: 90,
        groupBrthAmp: 0.08,
        groupBrthMin: 0.12,
        groupBrthMax: 0.24,
        radiusMin: 0,
        radiusMax: 128,
        radialAmpMin: 3,
        radialAmpMax: 8,
        angularAmpMin: 0.05,
        angularAmpMax: 0.14,
        speedMin: 0.35,
        speedMax: 0.72,
        sizeMin: 4,
        sizeMax: 10,
        weightMin: 2.3,
        weightMax: 4,
        alphaMin: 85,
        alphaMax: 195,
      },
    },
  // Parasite's attachment and recovery scales determine how long attention residue remains.
    parasite: {
      jitterSpeed: 0.015,
      jitterPosition: 8,
      jitterRotation: 0.36,
      jitterTurnWave: 0.134,
      attnAlphMin: 0.48,
      attnAlpMaxBas: 0.6,
      attnAlphMax: 1.25,
      attnShowMs: 4000,
      attnRestoreMs: 3000,
      attnBrnchPddng: 18,
      userGlowScl: 0.55,
    },
  // Deep Diver's sustained-attention window and feedback scales determine the depth of each dive.
    deepDiver: {
      userGlowAlph: 0.232,
      minSep: 18,
      sepStrength: 0.9,
      maxTypePush: 0.1,
      visualPush: 0.95,
      maxVisualPush: 0.1,
      mtnSpdMul: 1.6,
      mtnMaxFrmMs: 33.333,
      attnNearPddng: 18,
      attnDlyMs: 1000,
      attnLvGrcMs: 1500,
      attnTxMs: 1700,
      attnRestoreMs: 1500,
      attnLineScl: 0.86,
      spkBaseOtst: 4,
      attnSpkInst: 22,
      attnSpkTurnMs: 1700,
      attnSpkResMs: 1500,
      attnGrwthDlyMs: 9000,
      attnBodyDurMs: 6500,
      attnGlowIntrMs: 2500,
      attnGloIntScl: 1.7,
      attnGloIntAlp: 0.3944,
      attnGlowDurMs: 9000,
      attnGloResMs: 10000,
      attnBodyScl: 1.15,
      attnGlowScl: 10,
      attnGlowAlph: 0.2204,
      attnSpdScl: 0.2,
      rglrAlphScl: 0.9,
      innerScale: 0.82,
      blobScale: 1.04,
      lineStrkWght: 4.35,
      spkStrkWght: 7,
      ringStrkWght: 5.2,
      progStrkWght: 6,
      progressAlpha: 245,
      spkOtrLngth: 14,
      spkInnrLngth: 8,
      outlineWaveAmp: 5.5,
      outlineSpeed: 0.45,
      outlineSteps: 48,
      lineCchTps: 12,
      blobSegments: 48,
      blobCacheTps: 12,
      blobLayers: 5,
      blobWaveAmpl: 32,
      encnDlyMs: 3500,
      gazeHoldMs: 5000,
      focusFadeMs: 2000,
      focusCancelMs: 500,
      fcsEntryStrt: 0.05,
      fcsWndwApprMs: 7700,
      fcsWndwFadeMs: 6200,
      focusMoveMs: 9000,
      fcsAntcMs: 600,
      focusSettleMs: 700,
      focusCurveMin: 18,
      focusCurveMax: 30,
      fcsOvrsMin: 6,
      fcsOvrsMax: 10,
      focusTiltMax: 0.1,
      focusShapeMs: 3000,
      sharedHoldMs: 10000,
      leaveGraceMs: 2500,
      focusBreathMs: 2500,
      restHoldMs: 2500,
      focusExitMs: 5000,
      fcsLineScl: 0.86,
      fcsSpkInst: 22,
      focusRingScale: 0.85,
      focusRingMin: 1,
      focusRingMax: 3,
      focusRingLimit: 12,
      fcsRingGrowMs: 5000,
      fcsSpdScl: 0.2,
      focusSizeGain: 0.07,
      focusAlphaGain: 0.12,
      focusStackMax: 6,
      fcsWndwWdth: 145,
      fcsWndwHght: 220,
      fcsWndwMaxScl: 1.8,
      fcsWndwGain: 0.035,
      fcsWndwAlph: 248,
      fcsWndwBlur: 14,
      fcsWndwDistMin: -20,
      fcsWndwDistMax: 15,
      fcsInsdXMin: 4,
      fcsInsdXMax: 18,
      fcsInsdYMin: 30,
      fcsInsdYMax: 55,
      fcsDrftRadX: 10,
      fcsDrftRadY: 7,
      fcsDrftSpd: 0.33,
      fcsDrftFadeMs: 800,
      focusDriftTilt: 0.045,
      fcsSyncBrthMs: 3500,
      fcsSyncBrthAmp: 0.0105,
      focusBreathAmp: 0.04,
      focusTextSize: 11.65,
      focusFont: "Gloria Hallelujah",
      focusTextAlpha: 100,
      restTextColor: [189, 218, 166],
      restTextAlpha: 120,
      fcsTexGloBlu: 6,
      fcsTexGloAlp: 0.45,
      fcsTextShowMs: 10700,
      fcsTextFadeMs: 13700,
      fcsTextCovr: 0.84,
      focusTextInset: 21,
      fcsLttrSpcng: 1.25,
      fcsSentSpcs: 8,
      fcsTextWaveAmp: 3.1,
      fcsTexWavLng: 155,
      fcsTextWaveSpd: 0.06,
      fcsTextJttr: 1.6,
      focusTextTilt: 0,
      focusMessageMs: 2200,
      fcsMsgFadeEnd: 0.7,
      restMsgFadStr: 0.4,
      fcsBrthDrop: 16,
      fcsBbblOffst: 20,
      fcsBbblRise: 64,
      focusBubbleMin: 5,
      focusBubbleMax: 14,
      fcsBbblAlph: 100,
      fcsBbbGloAlp: 0.26,
      fcsBbbGloBlu: 3,
      fcsBbblDurMin: 4000,
      fcsBbblDurMax: 5000,
      fcsBbblDlyStep: 290,
      fcsBbblDlyJttr: 160,
      fcsBbblNMin: 2,
      fcsBbblNMax: 3,
      diffIniSizMin: 0.28,
      diffIniSizMax: 0.4,
      diffTgtSizeMin: 0.6,
      diffTgtSizeMax: 0.8,
    },
  // Roamer's division, movement, and recovery scales keep the direction of mind-wandering open.
    roamer: {
      userGlowScl: 1.38,
      userGlowAlph: 0.1624,
      minSep: 41,
      sepStrength: 0.1,
      sepBiasMin: 0.9,
      sepBiasMax: 1.2,
      sepFarChance: 0.25,
      sepFarMin: 1.2,
      sepFarMax: 1.4,
      sepSpdMul: 1.1,
      mtnSpdMul: 1.6,
      mtnMaxFrmMs: 33.333,
      arrowCount: 24,
      arrowGlowMin: 2,
      arrowGlowMax: 4,
      arrowGlowMs: 8000,
      arrowGlowEase: 0.025,
      arrowDotAlpha: 56,
      arrowDotSize: 9.9,
      arrowLitAlpha: 215,
      arrowGlowColor: [255, 255, 255],
      arrowGlowAlpha: 0.32,
      arrowGlowBlur: 3,
      bodyGlowAlpha: 0.14,
      edgeGlowAlpha: 0.24,
      lineGlowBlur: 9,
      bodyGlowBlur: 9,
      dotGlowAlpha: 0.26,
      dotGlowBlur: 10,
      arrowScale: 1.2,
      arrowScaleX: 0.8,
      arrowLitScale: 1.4,
      orbitBreathAmp: 0.14,
      orbitDriftAmp: 4.2,
      orbitSizeAmp: 0.18,
      orbitSpeed: 0.2,
      attnDlyMs: 1000,
      attnNearPddng: 18,
      attnGroupRad: 320,
      ixHitScl: 1.4,
      ixLvGrcMs: 2800,
      encnAvdPddng: 8,
      encnAvdPow: 0.025,
      encnAvdSpdScl: 0.6,
      attnSldDist: 50,
      attnSldSpdMul: 1.5,
      attnSldMaxFrmM: 33.333,
      attnSldEase: 0.07,
      attnResEas: 0.04,
      attnOrbitSpeed: 0.25,
      attnOrbtSpd: 0.2,
      spltActvMs: 3000,
      splitCaptureMs: 5000,
      spltCueBlnPrdM: 2500,
      spltCueBlnkN: 2,
      spltCueMinBrgh: 0.28,
      spltCueMaxScl: 1.6,
      spltRppSizMin: 30,
      spltRppSizMax: 80,
      spltCueRppAlp: 128,
      spltCueRppWgh: 1.5,
      spltCueRppGloA: 0.1,
      spltCueRppGloB: 4,
      spltArrBrtChn: 0.85,
      spltMinBrths: 2,
      splitBirthMs: 1800,
      spltBrtGloHolM: 8000,
      spltDistMin: 18,
      spltDistMax: 52,
      splitDriftMs: 10000,
      splitStaggerMs: 0,
      spltIniSizRtMi: 0.2,
      spltIniSizRtMa: 0.4,
      spltTgtSizRtMi: 0.75,
      spltTgtSizRtMa: 1.15,
      splitGrowthMs: 60000,
      diffColor: [101, 190, 255],
      diffIniSizMin: 0.12,
      diffIniSizMax: 0.2,
      diffTgtSizeMin: 0.38,
      diffTgtSizeMax: 0.47,
      diffGrowthMs: 40000,
      spltChlDthDlyM: 10000,
      spltChlDthChn: 0.35,
      dthDurMs: 4000,
      dthFnlScl: 0.62,
      spltProgClr: [161, 215, 255],
      spltProgAlph: 240,
      spltProgWght: 5.4,
      bodyMtnSpd: 0.1,
      bodyDriftAmp: 2.1,
      linePlsAmp: 0.1,
      bodyWaveAmp: 2.5,
      bodyWaveSpeed: 3.4,
      bodyWaveSteps: 48,
      motionCacheTps: 6,
    },
    cruise: {
      roamer: { speed: 0.08, rx: 180, ry: 120, ...zones.roamer },
      deep: { speed: 0.02, rx: 30, ry: 24, ...zones.deepDiver },
      guard: { speed: 0.21, rx: 135, ry: 95, ...zones.guardian },
    },
    guardianRange: {
      edgeShare: 0.76,
      edgeInner: 0.86,
      edgeOuter: 1,
      roamInner: 0.68,
      verticalBias: 0.8,
      topY0: 0.01,
      topY1: 0.08,
      bottomY0: 0.88,
      bottomY1: 0.98,
      rightX0: 0.82,
      rightX1: 0.91,
    },
    };
  }

  const ecoConst = window.EcologyConstants;

  // 3. Parameters that determine the scale and operating rhythm of the entire ecology
  const eco = {
    seed: 9,
    simFps: 60,
    moveSpeed: 0.9,
    // simFps is used for time conversion; main rendering and
    // detail animation use renderFps and animTps respectively.
    renderFps: 30,
    animTps: 24,
    bgColor: "#0c256d",
    drawScale: 0.675906,
    lifeScale: {
      Predator: 1.1,
      Parasite: 1.35,
      Roamer: 2.1,
      DeepDiver: 1.03,
      Guardian: 0.8076024,
    },
    lifeType: ecoConst.lifeType,
    lifeColor: {
      Roamer: [101, 190, 255],
      DeepDiver: [255, 255, 255],
      Guardian: [163, 204, 131],
    },
  };

  // 4. Light, sound, lures, and caches share the runtime rhythm
  const renderConfig = Object.freeze({
    maxPxlDnsty: 1.5,
  });

  const testParams = window.AppContext.params;
  const visualTest = window.AppContext.mode.visualTest;
  const visualTestMs = 4000;
  const visTestWdth = 1200;
  const testViewHeight = 700;

  const glowConfig = Object.freeze({
    // The glow uses a reduced pixel resolution; when frame
    // synchronization is disabled, it refreshes at updateTps.
    resolutionScale: 0.75,
    updateTps: 10,
    syncRndrFrm: true,
    wideBlur: 9.5,
    wideAlpha: 0.132,
    coreBlur: 4,
    coreAlpha: 0.054,
  });
  const glowLayersOn = testParams.get("native-glow") !== "1";

  const soundConfig = Object.freeze({
    // The voice limit and event cooldown jointly control sound density.
    enabled: testParams.get("sound") !== "0",
    masterGain: 1.5,
    maximumVoices: 4,
    maximumPan: 0.7,
    pauseFadeMs: 500,
    resumeFadeMs: 900,
    cooldownMs: Object.freeze({
      "participant-join": 700,
      "eyes-close": 600,
      "eyes-open": 600,
      "predator-lure": 1500,
    }),
  });

  const predatorLure = Object.freeze({
    frstMinIntrMs: 8000,
    frstMaxIntrMs: 12000,
    minIntrMs: 8000,
    maxIntrMs: 60000,
    rtryIntrMs: 8000,
    flashPulseMs: 1000,
    flashGapMs: 500,
    flashCount: 2,
    flshMinAlph: 0.3,
    flshMaxAlph: 1,
    flshMaxScl: 1.065,
  });

  const lifeCache = Object.freeze({
    // Caching reduces the cost of repeatedly drawing stable forms,
    // while interaction and growth changes remain updated by each lifeform frame by frame.
    enabled: testParams.get("vector-render") !== "1",
    updateTps: 6,
    updtTpsByType: Object.freeze({}),
    maxCchRfrsh: 10,
    pixelDensity: 1,
    bounds: Object.freeze({
      Predator: Object.freeze({ width: 340, height: 260 }),
      Roamer: Object.freeze({ width: 240, height: 240 }),
      DeepDiver: Object.freeze({ width: 160, height: 160 }),
      Guardian: Object.freeze({ width: 220, height: 220 }),
    }),
  });

  const lifeGlow = Object.freeze({
    none: Object.freeze({ color: "rgba(0, 0, 0, 0)", blur: 0 }),
    predator: Object.freeze({
      color: "rgba(255, 255, 255, 0.27)",
      blur: 11,
    }),
    deepOuter: Object.freeze({
      color: "rgba(255, 255, 255, 0.25)",
      blur: 10,
    }),
    deepCore: Object.freeze({
      color: "rgba(255, 255, 255, 0.35)",
      blur: 10,
    }),
    guardian: Object.freeze({
      color: "rgba(255, 255, 255, 0.34)",
      blur: 8.5,
    }),
  });

  const zones = {
    predator: { y0: 0.01, y1: 1 },
    roamer: { y0: 0.26, y1: 0.92 },
    deepDiver: { y0: 0.38, y1: 0.99 },
    guardian: { y0: 0.01, y1: 0.99 },
  };

  const userImpactGlow = Object.freeze({
    scale: 1.4,
    alpha: 0.348,
    sourceScale: 1.12,
    srcAlphScl: 1.22,
    pulseScale: 0.065,
    pulseSpeed: 0.0038,
    fadeInMs: 1200,
    leaveHoldMs: 1000,
    fadeOutMs: 2000,
    bscCelBrtHolMs: 6000,
    relCellHoldMs: 27600,
    diffLifeHoldMs: 8000,
    fcsAlphScl: 1,
    smplAlphScl: 0.2552 / 0.348,
    color: Object.freeze([255, 255, 255]),
  });

  const lifespanScale = 1.2;
  const lifeMaxScl = 1.2;
  // 5. Determining how life changes also determines how attention exerts influence
  const lifeMechanism = Object.freeze({
    lifespanScale,
    clock: Object.freeze({
      activeRate: ecoConst.lifeRates.active,
      openUnttRate: ecoConst.lifeRates.openUnattended,
      closedRate: ecoConst.lifeRates.closed,
      prsnCnfrmMs: 1500,
      absenceDelayMs: 2 * 60 * 1000,
    }),
    capacity: Object.freeze({
      suggMin: 28,
      ovrlThresh: 75,
      hardMaximum: ecoConst.hardMaximum,
    }),
// I preserve a minimum population for each species,
// allowing different attentional states room to coexist.
    spcMins: ecoConst.minimumCounts,
    lifespanMs: Object.freeze({
      Predator: Object.freeze([
        16 * 60 * 1000 * lifespanScale,
        25 * 60 * 1000 * lifespanScale * lifeMaxScl,
      ]),
      Parasite: Object.freeze([
        16 * 60 * 1000,
        30 * 60 * 1000,
      ]),
      Roamer: Object.freeze([
        13 * 60 * 1000 * lifespanScale,
        15 * 60 * 1000 * lifespanScale * lifeMaxScl,
      ]),
      DeepDiver: Object.freeze([
        15 * 60 * 1000 * lifespanScale,
        18 * 60 * 1000 * lifespanScale * lifeMaxScl,
      ]),
      Guardian: Object.freeze([
        20 * 60 * 1000 * lifespanScale,
        23 * 60 * 1000 * lifespanScale * lifeMaxScl,
      ]),
    }),
    prdtIxExtndMs: 5 * 60 * 1000,
    predatorTail: Object.freeze({
      extendAnimMs: 1000,
      extendGlowAlph: 235,
      extendGlowBlur: 18,
      visualScaleMin: 0.35,
      visualScaleMax: 3.8,
    }),
    safeGraceMs: 6000,
    vitlDurMs: 10000,
    fade: Object.freeze({
      startMs: 6000,
      durationMs: 5000,
      finalScale: 0.7,
    }),
    transform: Object.freeze({
      chance: 0.28,
      startMs: 6000,
      durationMs: 4000,
      birthDelayMs: 2500,
      finalScale: 0.6,
      parsGrwthMs: 40000,
    }),
    activity: Object.freeze({
      fnlMoveScl: 0.35,
      fnlPlsScl: 0.3,
    }),
    overload: Object.freeze({
      compressionMin: 2,
      compressionMax: 3,
      cooldownMs: 6000,
      durationMs: 4000,
      parsBrthDlyMs: 2500,
      finalScale: 0.6,
    }),
  });

  const settings = create({
    eco,
    zones,
    userGlow: userImpactGlow,
  });

  const driftMode = {
    roamer: {
      ttSpd: 0.0050301,
      n2Off: 333,
      dx: 45,
      sinY: 15,
      noiseY: 15,
      rotN: 0.1,
      bFreq: 1.4,
      bAmp: 0.04,
    },
    deep: {
      ttSpd: 0.003645,
      n2Off: 777,
      dx: 12,
      sinY: 12,
      noiseY: 12,
      rotN: 0.1,
      bFreq: 1.2,
      bAmp: 0.035,
    },
    guard: {
      ttSpd: 0.0048114,
      n2Off: 222,
      dx: 45,
      sinY: 24,
      noiseY: 18,
      rotN: 0.08,
      bFreq: 1,
      bAmp: 0.03,
    },
  };

  // 6. This ecological scale flows into every lifeform and system
  // SketchConfig is the current runtime configuration.
  window.SketchConfig = Object.freeze({
    eco,
    renderConfig,
    testParams,
    visualTest,
    visualTestMs,
    visTestWdth,
    testViewHeight,
    glowConfig,
    glowLayersOn,
    soundConfig,
    predatorLure,
    lifeCache,
    lifeGlow,
    lifeMechanism,
    zones,
    settings,
    driftMode,
  });
})();
